
module.exports = [
    '/',
    '/browse',
    '/search',
    '/project',
    '/view/:id',
    '/u/:id/profile',
    '/a/:id/profile',
    '/deposit',
    '/about',
    '/help',
    '/news',
    '/news/:id',
    '/events',
    '/events/id',
    '/forum',
    '/forum/thread/:id',
    '/forum/newsubject',
    '/login',
    '/user_list',
];
