image: docker:18-git

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  CI_REGISTRY_IMAGE: registry.gitlab.com/polaris-os-group/polaris-os

services:
  - docker:18-dind

stages:
    - Build
    - Deploy

before_script:
  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin registry.gitlab.com

Build and Push image:
  stage: Build
  tags:
    - test
  only:
    - INTEGRATION-INSERM
  script:
    - docker build -t $CI_REGISTRY_IMAGE:INSERM .
    - docker push $CI_REGISTRY_IMAGE:INSERM

Deploy test infra:
  stage: Deploy
  tags:
    - test
  only:
    - INTEGRATION-INSERM
  script:
    - docker stack deploy -c docker-compose.yml --resolve-image changed --with-registry-auth test
