image: docker:18.09.7-dind

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  CI_REGISTRY_IMAGE: registry.gitlab.com/polaris-os-group/polaris-os

services:
  - docker:18-dind

stages:
    - Build
    - Deploy

before_script:
  - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin registry.gitlab.com

Build and Push image production:
  stage: Build
  tags:
    - docker-test
  only:
    - client/INSERM
    - client/INED
  script:
    - apk add jq
    - export VERSION=$(cat package.json | jq -r .version)
    - docker info
    - docker build -t $CI_REGISTRY_IMAGE:$VERSION .
    - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin registry.gitlab.com
    - docker push $CI_REGISTRY_IMAGE:$VERSION

Build and Push image integration:
  stage: Build
  tags:
    - docker-test
  only:
    - INTEGRATION-INSERM
  script:
    - docker build -t $CI_REGISTRY_IMAGE:INSERM .
    - docker push $CI_REGISTRY_IMAGE:INSERM

Deploy test infra:
  stage: Deploy
  when: delayed
  start_in: 1 minutes
  tags:
    - docker-test
  only:
    - INTEGRATION-INSERM
  script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_IRDIRC_TEST01" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh mysciencework@${IP_IRDIRC_TEST01}
    - docker service update --force test_app

