variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  CI_REGISTRY_IMAGE: registry.gitlab.com/polaris-os-group/polaris-os
  DOCKER_TLS_CERTDIR: ""

stages:
  - Build
  # - Deploy

Build and Push image integration and production INSERM:
  image: docker:18.09.7
  stage: Build
  services:
    - docker:18.09.7-dind
  only:
    - client/INSERM
    - INTEGRATION-INSERM
  script:
    - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin registry.gitlab.com
    - docker build -t $CI_REGISTRY_IMAGE:INSERM .
    - docker push $CI_REGISTRY_IMAGE:INSERM

Deploy test infra:
  image: docker:18.09.7
  stage: Deploy
  variables:
    GIT_STRATEGY: none
  tags:
    - docker-test
  only:
    - INTEGRATION-INSERM
    - client/INSERM
  script:
    - 'which ssh-agent || ( apk update && apk add openssh-client )'
    - eval $(ssh-agent -s)
    - echo "$SSH_IRDIRC_TEST01" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh -o "StrictHostKeyChecking=no" -tt mysciencework@${IP_IRDIRC_TEST01} 'docker login registry.gitlab.com && docker pull registry.gitlab.com/polaris-os-group/polaris-os:INSERM && docker service update --with-registry-auth --image registry.gitlab.com/polaris-os-group/polaris-os:INSERM test_app'

# Deploy prod infra:
#   image: docker:18.09.7
#   stage: Deploy
#   variables:
#     GIT_STRATEGY: none
#   tags:
#     - docker-prod
#   only:
#     - client/INSERM
#   script:
#     - 'which ssh-agent || ( apk update && apk add openssh-client )'
#     - eval $(ssh-agent -s)
#     - echo "$SSH_IRDIRC_PROD01" | tr -d '\r' | ssh-add -
#     - mkdir -p ~/.ssh
#     - chmod 700 ~/.ssh
#     - ssh -o "StrictHostKeyChecking=no" -tt mysciencework@${IP_IRDIRC_PROD01} 'docker login registry.gitlab.com && docker pull registry.gitlab.com/polaris-os-group/polaris-os:INSERM && docker service update --with-registry-auth --image registry.gitlab.com/polaris-os-group/polaris-os:INSERM prod_app && docker service update --with-registry-auth --image registry.gitlab.com/polaris-os-group/polaris-os:INSERM prod_app-nginx'

