module.exports = [{ label: 'Checkbox', value: 'checkbox' },
  { label: 'Date', value: 'date' },
  { label: 'Color', value: 'color' },
  { label: 'Date Year', value: 'date-year' },
  { label: 'Email', value: 'email' },
  { label: 'File', value: 'file' },
  { label: 'Hidden', value: 'hidden' },
  { label: 'HTML Editor', value: 'html-editor' },
  { label: 'Importer', value: 'importer' },
  { label: 'MultiSelect', value: 'multi-select' },
  { label: 'Number', value: 'number' },
  { label: 'Price', value: 'price' },
  { label: 'Password', value: 'password' },
  { label: 'Password (hashed in SHA1)', value: 'password-sha1' },
  { label: 'Phone', value: 'phone' },
  { label: 'Radio', value: 'radio' },
  { label: 'Select', value: 'select' },
  { label: 'Static HTML', value: 'static-html' },
  { label: 'Static List', value: 'static-list' },
  { label: 'Dynamic List', value: 'dynamic-list' },
  { label: 'Static Text', value: 'static-text' },
  { label: 'Subform', value: 'subform' },
  { label: 'Text', value: 'text' },
  { label: 'Textarea', value: 'textarea' },
  { label: 'Time', value: 'time' }];
