
module.exports = [
    { label: 'l_keyword_type', value: 'keyword' },
    { label: 'l_text_type', value: 'text' },
    { label: 'l_long_type', value: 'long' },
    { label: 'l_integer_type', value: 'integer' },
    { label: 'l_short_type', value: 'short' },
    { label: 'l_byte_type', value: 'byte' },
    { label: 'l_double_type', value: 'double' },
    { label: 'l_float_type', value: 'float' },
    { label: 'l_half_float_type', value: 'half_float' },
    { label: 'l_scaled_float_type', value: 'scaled_float' },
    { label: 'l_date_type', value: 'date' },
    { label: 'l_boolean_type', value: 'boolean' },
    { label: 'l_binary_type', value: 'binary' },
    { label: 'l_long_range_type', value: 'long_range' },
    { label: 'l_integer_range_type', value: 'integer_range' },
    { label: 'l_double_range_type', value: 'double_range' },
    { label: 'l_float_range_type', value: 'float_range' },
    { label: 'l_date_range_type', value: 'date_range' },
    { label: 'l_object_type', value: 'object' },
    { label: 'l_list_type', value: 'nested' },
    { label: 'l_entity_type', value: 'entity' },
];
