window.esdocSearchIndex = [
  [
    "polarisos/app/modules/auth/access_schema.js~filterschema",
    "function/index.html#static-function-FilterSchema",
    "<span>FilterSchema</span> <span class=\"search-result-import-path\">PolarisOS/app/modules/auth/access_schema.js</span>",
    "function"
  ],
  [
    "polarisos/app/modules/exceptions/generic.js~genericexception",
    "function/index.html#static-function-GenericException",
    "<span>GenericException</span> <span class=\"search-result-import-path\">PolarisOS/app/modules/exceptions/generic.js</span>",
    "function"
  ],
  [
    "polarisos/app/modules/entities/crud/odm.js~odm",
    "class/app/modules/entities/crud/odm.js~ODM.html",
    "<span>ODM</span> <span class=\"search-result-import-path\">PolarisOS/app/modules/entities/crud/odm.js</span>",
    "class"
  ],
  [
    "polarisos/app/modules/pipeline/pipeline.js~pipeline",
    "class/app/modules/pipeline/pipeline.js~Pipeline.html",
    "<span>Pipeline</span> <span class=\"search-result-import-path\">PolarisOS/app/modules/pipeline/pipeline.js</span>",
    "class"
  ],
  [
    "polarisos/app/modules/pipeline/validator/validator.js~validator",
    "class/app/modules/pipeline/validator/validator.js~Validator.html",
    "<span>Validator</span> <span class=\"search-result-import-path\">PolarisOS/app/modules/pipeline/validator/validator.js</span>",
    "class"
  ],
  [
    "polarisos/app/modules/utils/utils.js~_return_inner_object",
    "function/index.html#static-function-_return_inner_object",
    "<span>_return_inner_object</span> <span class=\"search-result-import-path\">PolarisOS/app/modules/utils/utils.js</span>",
    "function"
  ],
  [
    "polarisos/app/modules/utils/utils.js~_test_inner_object",
    "function/index.html#static-function-_test_inner_object",
    "<span>_test_inner_object</span> <span class=\"search-result-import-path\">PolarisOS/app/modules/utils/utils.js</span>",
    "function"
  ],
  [
    "polarisos/app/modules/entities/role/controllers/index.js~access",
    "function/index.html#static-function-access",
    "<span>access</span> <span class=\"search-result-import-path\">PolarisOS/app/modules/entities/role/controllers/index.js</span>",
    "function"
  ],
  [
    "polarisos/app/modules/entities/user/controllers/index.js~access",
    "function/index.html#static-function-access",
    "<span>access</span> <span class=\"search-result-import-path\">PolarisOS/app/modules/entities/user/controllers/index.js</span>",
    "function"
  ],
  [
    "polarisos/app/modules/utils/uploads.js~add_single",
    "function/index.html#static-function-add_single",
    "<span>add_single</span> <span class=\"search-result-import-path\">PolarisOS/app/modules/utils/uploads.js</span>",
    "function"
  ],
  [
    "polarisos/app/csl_styles/register.js~add_styles",
    "function/index.html#static-function-add_styles",
    "<span>add_styles</span> <span class=\"search-result-import-path\">PolarisOS/app/csl_styles/register.js</span>",
    "function"
  ],
  [
    "polarisos/app/modules/utils/router.js~api_middlewares",
    "function/index.html#static-function-api_middlewares",
    "<span>api_middlewares</span> <span class=\"search-result-import-path\">PolarisOS/app/modules/utils/router.js</span>",
    "function"
  ],
  [
    "polarisos/app/modules/utils/router.js~app_middlewares",
    "function/index.html#static-function-app_middlewares",
    "<span>app_middlewares</span> <span class=\"search-result-import-path\">PolarisOS/app/modules/utils/router.js</span>",
    "function"
  ],
  [
    "polarisos/app/modules/pipeline/transformer/transformer.js~apply_transducer",
    "function/index.html#static-function-apply_transducer",
    "<span>apply_transducer</span> <span class=\"search-result-import-path\">PolarisOS/app/modules/pipeline/transformer/transformer.js</span>",
    "function"
  ],
  [
    "polarisos/app/modules/entities/role/controllers/index.js~authenticate",
    "function/index.html#static-function-authenticate",
    "<span>authenticate</span> <span class=\"search-result-import-path\">PolarisOS/app/modules/entities/role/controllers/index.js</span>",
    "function"
  ],
  [
    "polarisos/app/modules/entities/user/controllers/index.js~authenticate",
    "function/index.html#static-function-authenticate",
    "<span>authenticate</span> <span class=\"search-result-import-path\">PolarisOS/app/modules/entities/user/controllers/index.js</span>",
    "function"
  ],
  [
    "polarisos/app/modules/utils/auth.js~cas_auth",
    "function/index.html#static-function-cas_auth",
    "<span>cas_auth</span> <span class=\"search-result-import-path\">PolarisOS/app/modules/utils/auth.js</span>",
    "function"
  ],
  [
    "polarisos/app/modules/pipeline/completer/completer.js~complete",
    "function/index.html#static-function-complete",
    "<span>complete</span> <span class=\"search-result-import-path\">PolarisOS/app/modules/pipeline/completer/completer.js</span>",
    "function"
  ],
  [
    "polarisos/app/modules/entities/crud/controllers/index.js~count",
    "function/index.html#static-function-count",
    "<span>count</span> <span class=\"search-result-import-path\">PolarisOS/app/modules/entities/crud/controllers/index.js</span>",
    "function"
  ],
  [
    "polarisos/app/create_indices.js~create",
    "function/index.html#static-function-create",
    "<span>create</span> <span class=\"search-result-import-path\">PolarisOS/app/create_indices.js</span>",
    "function"
  ],
  [
    "polarisos/app/modules/entities/crud/controllers/index.js~del",
    "function/index.html#static-function-del",
    "<span>del</span> <span class=\"search-result-import-path\">PolarisOS/app/modules/entities/crud/controllers/index.js</span>",
    "function"
  ],
  [
    "polarisos/app/modules/utils/router.js~del_middlewares",
    "function/index.html#static-function-del_middlewares",
    "<span>del_middlewares</span> <span class=\"search-result-import-path\">PolarisOS/app/modules/utils/router.js</span>",
    "function"
  ],
  [
    "polarisos/app/modules/pipeline/completer/complfunctions/index.js~denormalization",
    "function/index.html#static-function-denormalization",
    "<span>denormalization</span> <span class=\"search-result-import-path\">PolarisOS/app/modules/pipeline/completer/complfunctions/index.js</span>",
    "function"
  ],
  [
    "polarisos/app/modules/utils/auth.js~do_standard_checks",
    "function/index.html#static-function-do_standard_checks",
    "<span>do_standard_checks</span> <span class=\"search-result-import-path\">PolarisOS/app/modules/utils/auth.js</span>",
    "function"
  ],
  [
    "polarisos/app/modules/utils/uploads.js~download",
    "function/index.html#static-function-download",
    "<span>download</span> <span class=\"search-result-import-path\">PolarisOS/app/modules/utils/uploads.js</span>",
    "function"
  ],
  [
    "polarisos/app/modules/utils/bibtex.js~escape_from_bibtex",
    "function/index.html#static-function-escape_from_bibtex",
    "<span>escape_from_bibtex</span> <span class=\"search-result-import-path\">PolarisOS/app/modules/utils/bibtex.js</span>",
    "function"
  ],
  [
    "polarisos/app/modules/utils/bibtex.js~escape_to_bibtex",
    "function/index.html#static-function-escape_to_bibtex",
    "<span>escape_to_bibtex</span> <span class=\"search-result-import-path\">PolarisOS/app/modules/utils/bibtex.js</span>",
    "function"
  ],
  [
    "polarisos/app/modules/pipeline/formatter/formatfunctions/index.js~filter_empty_or_null_objects",
    "function/index.html#static-function-filter_empty_or_null_objects",
    "<span>filter_empty_or_null_objects</span> <span class=\"search-result-import-path\">PolarisOS/app/modules/pipeline/formatter/formatfunctions/index.js</span>",
    "function"
  ],
  [
    "polarisos/app/modules/utils/utils.js~filter_empty_or_null_objects",
    "function/index.html#static-function-filter_empty_or_null_objects",
    "<span>filter_empty_or_null_objects</span> <span class=\"search-result-import-path\">PolarisOS/app/modules/utils/utils.js</span>",
    "function"
  ],
  [
    "polarisos/app/modules/utils/utils.js~find_object_with_path",
    "function/index.html#static-function-find_object_with_path",
    "<span>find_object_with_path</span> <span class=\"search-result-import-path\">PolarisOS/app/modules/utils/utils.js</span>",
    "function"
  ],
  [
    "polarisos/app/modules/utils/utils.js~find_popvalue_with_path",
    "function/index.html#static-function-find_popvalue_with_path",
    "<span>find_popvalue_with_path</span> <span class=\"search-result-import-path\">PolarisOS/app/modules/utils/utils.js</span>",
    "function"
  ],
  [
    "polarisos/app/modules/utils/auth.js~find_through_ldap",
    "function/index.html#static-function-find_through_ldap",
    "<span>find_through_ldap</span> <span class=\"search-result-import-path\">PolarisOS/app/modules/utils/auth.js</span>",
    "function"
  ],
  [
    "polarisos/app/modules/utils/auth.js~find_user",
    "function/index.html#static-function-find_user",
    "<span>find_user</span> <span class=\"search-result-import-path\">PolarisOS/app/modules/utils/auth.js</span>",
    "function"
  ],
  [
    "polarisos/app/modules/utils/utils.js~find_value_with_path",
    "function/index.html#static-function-find_value_with_path",
    "<span>find_value_with_path</span> <span class=\"search-result-import-path\">PolarisOS/app/modules/utils/utils.js</span>",
    "function"
  ],
  [
    "polarisos/app/modules/pipeline/transformer/transfunctions/index.js~flatten",
    "function/index.html#static-function-flatten",
    "<span>flatten</span> <span class=\"search-result-import-path\">PolarisOS/app/modules/pipeline/transformer/transfunctions/index.js</span>",
    "function"
  ],
  [
    "polarisos/app/modules/utils/web.js~forge_ok_response",
    "function/index.html#static-function-forge_ok_response",
    "<span>forge_ok_response</span> <span class=\"search-result-import-path\">PolarisOS/app/modules/utils/web.js</span>",
    "function"
  ],
  [
    "polarisos/app/modules/utils/utils.js~forge_whitelist_blacklist_query",
    "function/index.html#static-function-forge_whitelist_blacklist_query",
    "<span>forge_whitelist_blacklist_query</span> <span class=\"search-result-import-path\">PolarisOS/app/modules/utils/utils.js</span>",
    "function"
  ],
  [
    "polarisos/app/modules/pipeline/formatter/formatter.js~format",
    "function/index.html#static-function-format",
    "<span>format</span> <span class=\"search-result-import-path\">PolarisOS/app/modules/pipeline/formatter/formatter.js</span>",
    "function"
  ],
  [
    "polarisos/app/modules/pipeline/formatter/formatfunctions/index.js~format_string",
    "function/index.html#static-function-format_string",
    "<span>format_string</span> <span class=\"search-result-import-path\">PolarisOS/app/modules/pipeline/formatter/formatfunctions/index.js</span>",
    "function"
  ],
  [
    "polarisos/app/modules/pipeline/formatter/formatter.js~formatting",
    "function/index.html#static-function-formatting",
    "<span>formatting</span> <span class=\"search-result-import-path\">PolarisOS/app/modules/pipeline/formatter/formatter.js</span>",
    "function"
  ],
  [
    "polarisos/app/modules/utils/router.js~generate_del_routes",
    "function/index.html#static-function-generate_del_routes",
    "<span>generate_del_routes</span> <span class=\"search-result-import-path\">PolarisOS/app/modules/utils/router.js</span>",
    "function"
  ],
  [
    "polarisos/app/modules/utils/router.js~generate_entity_routes",
    "function/index.html#static-function-generate_entity_routes",
    "<span>generate_entity_routes</span> <span class=\"search-result-import-path\">PolarisOS/app/modules/utils/router.js</span>",
    "function"
  ],
  [
    "polarisos/app/modules/utils/router.js~generate_get_routes",
    "function/index.html#static-function-generate_get_routes",
    "<span>generate_get_routes</span> <span class=\"search-result-import-path\">PolarisOS/app/modules/utils/router.js</span>",
    "function"
  ],
  [
    "polarisos/app/modules/utils/router.js~generate_gets_routes",
    "function/index.html#static-function-generate_gets_routes",
    "<span>generate_gets_routes</span> <span class=\"search-result-import-path\">PolarisOS/app/modules/utils/router.js</span>",
    "function"
  ],
  [
    "polarisos/app/modules/utils/crypto.js~generate_key",
    "function/index.html#static-function-generate_key",
    "<span>generate_key</span> <span class=\"search-result-import-path\">PolarisOS/app/modules/utils/crypto.js</span>",
    "function"
  ],
  [
    "polarisos/app/modules/utils/router.js~generate_post_routes",
    "function/index.html#static-function-generate_post_routes",
    "<span>generate_post_routes</span> <span class=\"search-result-import-path\">PolarisOS/app/modules/utils/router.js</span>",
    "function"
  ],
  [
    "polarisos/app/modules/utils/router.js~generate_put_routes",
    "function/index.html#static-function-generate_put_routes",
    "<span>generate_put_routes</span> <span class=\"search-result-import-path\">PolarisOS/app/modules/utils/router.js</span>",
    "function"
  ],
  [
    "polarisos/app/modules/3rdparty/rss/controllers.js~generate_rss_feed",
    "function/index.html#static-function-generate_rss_feed",
    "<span>generate_rss_feed</span> <span class=\"search-result-import-path\">PolarisOS/app/modules/3rdparty/rss/controllers.js</span>",
    "function"
  ],
  [
    "polarisos/app/modules/utils/crypto.js~generate_secret",
    "function/index.html#static-function-generate_secret",
    "<span>generate_secret</span> <span class=\"search-result-import-path\">PolarisOS/app/modules/utils/crypto.js</span>",
    "function"
  ],
  [
    "polarisos/app/modules/pipeline/completer/complfunctions/index.js~generic_complete",
    "function/index.html#static-function-generic_complete",
    "<span>generic_complete</span> <span class=\"search-result-import-path\">PolarisOS/app/modules/pipeline/completer/complfunctions/index.js</span>",
    "function"
  ],
  [
    "polarisos/app/modules/pipeline/formatter/formatfunctions/index.js~generic_formatter",
    "function/index.html#static-function-generic_formatter",
    "<span>generic_formatter</span> <span class=\"search-result-import-path\">PolarisOS/app/modules/pipeline/formatter/formatfunctions/index.js</span>",
    "function"
  ],
  [
    "polarisos/app/modules/entities/crud/controllers/index.js~get",
    "function/index.html#static-function-get",
    "<span>get</span> <span class=\"search-result-import-path\">PolarisOS/app/modules/entities/crud/controllers/index.js</span>",
    "function"
  ],
  [
    "polarisos/app/modules/entities/exporter/controllers/hal.js~get_author_info",
    "function/index.html#static-function-get_author_info",
    "<span>get_author_info</span> <span class=\"search-result-import-path\">PolarisOS/app/modules/entities/exporter/controllers/hal.js</span>",
    "function"
  ],
  [
    "polarisos/app/modules/utils/auth.js~get_cas_info",
    "function/index.html#static-function-get_cas_info",
    "<span>get_cas_info</span> <span class=\"search-result-import-path\">PolarisOS/app/modules/utils/auth.js</span>",
    "function"
  ],
  [
    "polarisos/app/modules/utils/lang.js~get_config",
    "function/index.html#static-function-get_config",
    "<span>get_config</span> <span class=\"search-result-import-path\">PolarisOS/app/modules/utils/lang.js</span>",
    "function"
  ],
  [
    "polarisos/app/modules/entities/exporter/controllers/hal.js~get_edition_stmt",
    "function/index.html#static-function-get_edition_stmt",
    "<span>get_edition_stmt</span> <span class=\"search-result-import-path\">PolarisOS/app/modules/entities/exporter/controllers/hal.js</span>",
    "function"
  ],
  [
    "polarisos/app/modules/pipeline/transformer/transfunctions/index.js~get_in_list",
    "function/index.html#static-function-get_in_list",
    "<span>get_in_list</span> <span class=\"search-result-import-path\">PolarisOS/app/modules/pipeline/transformer/transfunctions/index.js</span>",
    "function"
  ],
  [
    "polarisos/app/modules/utils/lang.js~get_language_values",
    "function/index.html#static-function-get_language_values",
    "<span>get_language_values</span> <span class=\"search-result-import-path\">PolarisOS/app/modules/utils/lang.js</span>",
    "function"
  ],
  [
    "polarisos/app/modules/utils/lang.js~get_language_values_from_langs",
    "function/index.html#static-function-get_language_values_from_langs",
    "<span>get_language_values_from_langs</span> <span class=\"search-result-import-path\">PolarisOS/app/modules/utils/lang.js</span>",
    "function"
  ],
  [
    "polarisos/app/modules/utils/lang.js~get_language_values_from_langs_and_keys",
    "function/index.html#static-function-get_language_values_from_langs_and_keys",
    "<span>get_language_values_from_langs_and_keys</span> <span class=\"search-result-import-path\">PolarisOS/app/modules/utils/lang.js</span>",
    "function"
  ],
  [
    "polarisos/app/modules/utils/router.js~get_middlewares",
    "function/index.html#static-function-get_middlewares",
    "<span>get_middlewares</span> <span class=\"search-result-import-path\">PolarisOS/app/modules/utils/router.js</span>",
    "function"
  ],
  [
    "polarisos/app/modules/entities/exporter/controllers/hal.js~get_monogr",
    "function/index.html#static-function-get_monogr",
    "<span>get_monogr</span> <span class=\"search-result-import-path\">PolarisOS/app/modules/entities/exporter/controllers/hal.js</span>",
    "function"
  ],
  [
    "polarisos/app/modules/entities/exporter/controllers/hal.js~get_notes_stmt",
    "function/index.html#static-function-get_notes_stmt",
    "<span>get_notes_stmt</span> <span class=\"search-result-import-path\">PolarisOS/app/modules/entities/exporter/controllers/hal.js</span>",
    "function"
  ],
  [
    "polarisos/app/modules/entities/exporter/controllers/hal.js~get_profile_desc",
    "function/index.html#static-function-get_profile_desc",
    "<span>get_profile_desc</span> <span class=\"search-result-import-path\">PolarisOS/app/modules/entities/exporter/controllers/hal.js</span>",
    "function"
  ],
  [
    "polarisos/app/modules/entities/exporter/controllers/hal.js~get_publication_stmt",
    "function/index.html#static-function-get_publication_stmt",
    "<span>get_publication_stmt</span> <span class=\"search-result-import-path\">PolarisOS/app/modules/entities/exporter/controllers/hal.js</span>",
    "function"
  ],
  [
    "polarisos/app/modules/entities/exporter/controllers/hal.js~get_series_stmt",
    "function/index.html#static-function-get_series_stmt",
    "<span>get_series_stmt</span> <span class=\"search-result-import-path\">PolarisOS/app/modules/entities/exporter/controllers/hal.js</span>",
    "function"
  ],
  [
    "polarisos/app/modules/utils/mailer.js~get_smtp_transport",
    "function/index.html#static-function-get_smtp_transport",
    "<span>get_smtp_transport</span> <span class=\"search-result-import-path\">PolarisOS/app/modules/utils/mailer.js</span>",
    "function"
  ],
  [
    "polarisos/app/modules/entities/crud/mapper.js~get_sort",
    "function/index.html#static-function-get_sort",
    "<span>get_sort</span> <span class=\"search-result-import-path\">PolarisOS/app/modules/entities/crud/mapper.js</span>",
    "function"
  ],
  [
    "polarisos/app/modules/entities/exporter/controllers/hal.js~get_source_desc",
    "function/index.html#static-function-get_source_desc",
    "<span>get_source_desc</span> <span class=\"search-result-import-path\">PolarisOS/app/modules/entities/exporter/controllers/hal.js</span>",
    "function"
  ],
  [
    "polarisos/app/modules/entities/exporter/controllers/hal.js~get_title_stmt",
    "function/index.html#static-function-get_title_stmt",
    "<span>get_title_stmt</span> <span class=\"search-result-import-path\">PolarisOS/app/modules/entities/exporter/controllers/hal.js</span>",
    "function"
  ],
  [
    "polarisos/app/modules/entities/crud/controllers/index.js~gets",
    "function/index.html#static-function-gets",
    "<span>gets</span> <span class=\"search-result-import-path\">PolarisOS/app/modules/entities/crud/controllers/index.js</span>",
    "function"
  ],
  [
    "polarisos/app/modules/utils/utils.js~hasproperty",
    "function/index.html#static-function-hasProperty",
    "<span>hasProperty</span> <span class=\"search-result-import-path\">PolarisOS/app/modules/utils/utils.js</span>",
    "function"
  ],
  [
    "polarisos/app/modules/pipeline/transformer/transfunctions/index.js~identity",
    "function/index.html#static-function-identity",
    "<span>identity</span> <span class=\"search-result-import-path\">PolarisOS/app/modules/pipeline/transformer/transfunctions/index.js</span>",
    "function"
  ],
  [
    "polarisos/app/modules/pipeline/validator/valfunctions/checks.js~if_exists",
    "function/index.html#static-function-if_exists",
    "<span>if_exists</span> <span class=\"search-result-import-path\">PolarisOS/app/modules/pipeline/validator/valfunctions/checks.js</span>",
    "function"
  ],
  [
    "polarisos/app/modules/pipeline/completer/complfunctions/index.js~initial",
    "function/index.html#static-function-initial",
    "<span>initial</span> <span class=\"search-result-import-path\">PolarisOS/app/modules/pipeline/completer/complfunctions/index.js</span>",
    "function"
  ],
  [
    "polarisos/app/initializations/routes.js~initialize_routes",
    "function/index.html#static-function-initialize_routes",
    "<span>initialize_routes</span> <span class=\"search-result-import-path\">PolarisOS/app/initializations/routes.js</span>",
    "function"
  ],
  [
    "polarisos/app/modules/utils/utils.js~isnil",
    "function/index.html#static-function-isNil",
    "<span>isNil</span> <span class=\"search-result-import-path\">PolarisOS/app/modules/utils/utils.js</span>",
    "function"
  ],
  [
    "polarisos/app/modules/pipeline/validator/valfunctions/checks.js~is_conditioned_on",
    "function/index.html#static-function-is_conditioned_on",
    "<span>is_conditioned_on</span> <span class=\"search-result-import-path\">PolarisOS/app/modules/pipeline/validator/valfunctions/checks.js</span>",
    "function"
  ],
  [
    "polarisos/app/modules/pipeline/validator/valfunctions/checks.js~is_unique",
    "function/index.html#static-function-is_unique",
    "<span>is_unique</span> <span class=\"search-result-import-path\">PolarisOS/app/modules/pipeline/validator/valfunctions/checks.js</span>",
    "function"
  ],
  [
    "polarisos/app/modules/pipeline/validator/valfunctions/checks.js~is_valid_json",
    "function/index.html#static-function-is_valid_json",
    "<span>is_valid_json</span> <span class=\"search-result-import-path\">PolarisOS/app/modules/pipeline/validator/valfunctions/checks.js</span>",
    "function"
  ],
  [
    "polarisos/app/modules/utils/streams.js~is_valid_stream",
    "function/index.html#static-function-is_valid_stream",
    "<span>is_valid_stream</span> <span class=\"search-result-import-path\">PolarisOS/app/modules/utils/streams.js</span>",
    "function"
  ],
  [
    "polarisos/app/modules/pipeline/completer/complfunctions/index.js~key_complete",
    "function/index.html#static-function-key_complete",
    "<span>key_complete</span> <span class=\"search-result-import-path\">PolarisOS/app/modules/pipeline/completer/complfunctions/index.js</span>",
    "function"
  ],
  [
    "polarisos/app/modules/utils/router.js~koa_middlewares",
    "function/index.html#static-function-koa_middlewares",
    "<span>koa_middlewares</span> <span class=\"search-result-import-path\">PolarisOS/app/modules/utils/router.js</span>",
    "function"
  ],
  [
    "polarisos/app/modules/utils/auth.js~login_auth",
    "function/index.html#static-function-login_auth",
    "<span>login_auth</span> <span class=\"search-result-import-path\">PolarisOS/app/modules/utils/auth.js</span>",
    "function"
  ],
  [
    "polarisos/app/modules/utils/utils.js~make_nested_object_from_path",
    "function/index.html#static-function-make_nested_object_from_path",
    "<span>make_nested_object_from_path</span> <span class=\"search-result-import-path\">PolarisOS/app/modules/utils/utils.js</span>",
    "function"
  ],
  [
    "polarisos/app/modules/utils/auth.js~map_ldap_to_pos",
    "function/index.html#static-function-map_ldap_to_pos",
    "<span>map_ldap_to_pos</span> <span class=\"search-result-import-path\">PolarisOS/app/modules/utils/auth.js</span>",
    "function"
  ],
  [
    "polarisos/app/modules/utils/utils.js~merge_with_concat",
    "function/index.html#static-function-merge_with_concat",
    "<span>merge_with_concat</span> <span class=\"search-result-import-path\">PolarisOS/app/modules/utils/utils.js</span>",
    "function"
  ],
  [
    "polarisos/app/modules/utils/utils.js~merge_with_replacement",
    "function/index.html#static-function-merge_with_replacement",
    "<span>merge_with_replacement</span> <span class=\"search-result-import-path\">PolarisOS/app/modules/utils/utils.js</span>",
    "function"
  ],
  [
    "polarisos/app/modules/utils/utils.js~merge_with_superposition",
    "function/index.html#static-function-merge_with_superposition",
    "<span>merge_with_superposition</span> <span class=\"search-result-import-path\">PolarisOS/app/modules/utils/utils.js</span>",
    "function"
  ],
  [
    "polarisos/app/modules/utils/uploads.js~multi_download",
    "function/index.html#static-function-multi_download",
    "<span>multi_download</span> <span class=\"search-result-import-path\">PolarisOS/app/modules/utils/uploads.js</span>",
    "function"
  ],
  [
    "polarisos/app/modules/pipeline/formatter/formatfunctions/index.js~oarray_to_array",
    "function/index.html#static-function-oarray_to_array",
    "<span>oarray_to_array</span> <span class=\"search-result-import-path\">PolarisOS/app/modules/pipeline/formatter/formatfunctions/index.js</span>",
    "function"
  ],
  [
    "polarisos/app/modules/entities/crud/controllers/index.js~post",
    "function/index.html#static-function-post",
    "<span>post</span> <span class=\"search-result-import-path\">PolarisOS/app/modules/entities/crud/controllers/index.js</span>",
    "function"
  ],
  [
    "polarisos/app/modules/utils/router.js~post_middlewares",
    "function/index.html#static-function-post_middlewares",
    "<span>post_middlewares</span> <span class=\"search-result-import-path\">PolarisOS/app/modules/utils/router.js</span>",
    "function"
  ],
  [
    "polarisos/app/modules/entities/crud/controllers/index.js~post_with_action",
    "function/index.html#static-function-post_with_action",
    "<span>post_with_action</span> <span class=\"search-result-import-path\">PolarisOS/app/modules/entities/crud/controllers/index.js</span>",
    "function"
  ],
  [
    "polarisos/app/modules/entities/crud/controllers/index.js~put",
    "function/index.html#static-function-put",
    "<span>put</span> <span class=\"search-result-import-path\">PolarisOS/app/modules/entities/crud/controllers/index.js</span>",
    "function"
  ],
  [
    "polarisos/app/modules/utils/router.js~put_middlewares",
    "function/index.html#static-function-put_middlewares",
    "<span>put_middlewares</span> <span class=\"search-result-import-path\">PolarisOS/app/modules/utils/router.js</span>",
    "function"
  ],
  [
    "polarisos/app/modules/entities/crud/controllers/index.js~put_with_action",
    "function/index.html#static-function-put_with_action",
    "<span>put_with_action</span> <span class=\"search-result-import-path\">PolarisOS/app/modules/entities/crud/controllers/index.js</span>",
    "function"
  ],
  [
    "polarisos/app/modules/utils/lang.js~retrieve_single_quantity",
    "function/index.html#static-function-retrieve_single_quantity",
    "<span>retrieve_single_quantity</span> <span class=\"search-result-import-path\">PolarisOS/app/modules/utils/lang.js</span>",
    "function"
  ],
  [
    "polarisos/app/modules/3rdparty/rss/routes.js~routes",
    "function/index.html#static-function-routes",
    "<span>routes</span> <span class=\"search-result-import-path\">PolarisOS/app/modules/3rdparty/rss/routes.js</span>",
    "function"
  ],
  [
    "polarisos/app/modules/entities/user/routes/index.js~routes",
    "function/index.html#static-function-routes",
    "<span>routes</span> <span class=\"search-result-import-path\">PolarisOS/app/modules/entities/user/routes/index.js</span>",
    "function"
  ],
  [
    "polarisos/app/modules/entities/crud/controllers/index.js~search",
    "function/index.html#static-function-search",
    "<span>search</span> <span class=\"search-result-import-path\">PolarisOS/app/modules/entities/crud/controllers/index.js</span>",
    "function"
  ],
  [
    "polarisos/app/modules/pipeline/completer/complfunctions/index.js~secret_complete",
    "function/index.html#static-function-secret_complete",
    "<span>secret_complete</span> <span class=\"search-result-import-path\">PolarisOS/app/modules/pipeline/completer/complfunctions/index.js</span>",
    "function"
  ],
  [
    "polarisos/app/modules/entities/mswpublication/controllers/index.js~send_email",
    "function/index.html#static-function-send_email",
    "<span>send_email</span> <span class=\"search-result-import-path\">PolarisOS/app/modules/entities/mswpublication/controllers/index.js</span>",
    "function"
  ],
  [
    "polarisos/app/modules/utils/mailer.js~send_email",
    "function/index.html#static-function-send_email",
    "<span>send_email</span> <span class=\"search-result-import-path\">PolarisOS/app/modules/utils/mailer.js</span>",
    "function"
  ],
  [
    "polarisos/app/modules/utils/mailer.js~send_email_through_smtp",
    "function/index.html#static-function-send_email_through_smtp",
    "<span>send_email_through_smtp</span> <span class=\"search-result-import-path\">PolarisOS/app/modules/utils/mailer.js</span>",
    "function"
  ],
  [
    "polarisos/app/modules/utils/mailer.js~send_email_with",
    "function/index.html#static-function-send_email_with",
    "<span>send_email_with</span> <span class=\"search-result-import-path\">PolarisOS/app/modules/utils/mailer.js</span>",
    "function"
  ],
  [
    "polarisos/app/modules/pipeline/formatter/formatfunctions/index.js~set_default_lang_for_array",
    "function/index.html#static-function-set_default_lang_for_array",
    "<span>set_default_lang_for_array</span> <span class=\"search-result-import-path\">PolarisOS/app/modules/pipeline/formatter/formatfunctions/index.js</span>",
    "function"
  ],
  [
    "polarisos/app/modules/utils/xml.js~strip_xhtml_tags",
    "function/index.html#static-function-strip_xhtml_tags",
    "<span>strip_xhtml_tags</span> <span class=\"search-result-import-path\">PolarisOS/app/modules/utils/xml.js</span>",
    "function"
  ],
  [
    "polarisos/app/modules/pipeline/transformer/transfunctions/index.js~template_identity",
    "function/index.html#static-function-template_identity",
    "<span>template_identity</span> <span class=\"search-result-import-path\">PolarisOS/app/modules/pipeline/transformer/transfunctions/index.js</span>",
    "function"
  ],
  [
    "polarisos/app/modules/utils/streams.js~to_array",
    "function/index.html#static-function-to_array",
    "<span>to_array</span> <span class=\"search-result-import-path\">PolarisOS/app/modules/utils/streams.js</span>",
    "function"
  ],
  [
    "polarisos/app/modules/utils/streams.js~to_buffer",
    "function/index.html#static-function-to_buffer",
    "<span>to_buffer</span> <span class=\"search-result-import-path\">PolarisOS/app/modules/utils/streams.js</span>",
    "function"
  ],
  [
    "polarisos/app/modules/utils/xml.js~to_object",
    "function/index.html#static-function-to_object",
    "<span>to_object</span> <span class=\"search-result-import-path\">PolarisOS/app/modules/utils/xml.js</span>",
    "function"
  ],
  [
    "polarisos/app/modules/pipeline/transformer/transformer.js~transform",
    "function/index.html#static-function-transform",
    "<span>transform</span> <span class=\"search-result-import-path\">PolarisOS/app/modules/pipeline/transformer/transformer.js</span>",
    "function"
  ],
  [
    "polarisos/app/modules/entities/exporter/controllers/hal.js~transform_publication_to_hal",
    "function/index.html#static-function-transform_publication_to_hal",
    "<span>transform_publication_to_hal</span> <span class=\"search-result-import-path\">PolarisOS/app/modules/entities/exporter/controllers/hal.js</span>",
    "function"
  ],
  [
    "polarisos/app/modules/entities/crud/mapper.js~transform_to_aggregation",
    "function/index.html#static-function-transform_to_aggregation",
    "<span>transform_to_aggregation</span> <span class=\"search-result-import-path\">PolarisOS/app/modules/entities/crud/mapper.js</span>",
    "function"
  ],
  [
    "polarisos/app/modules/entities/crud/mapper.js~transform_to_search",
    "function/index.html#static-function-transform_to_search",
    "<span>transform_to_search</span> <span class=\"search-result-import-path\">PolarisOS/app/modules/entities/crud/mapper.js</span>",
    "function"
  ],
  [
    "polarisos/app/modules/entities/crud/mapper.js~transform_to_sort",
    "function/index.html#static-function-transform_to_sort",
    "<span>transform_to_sort</span> <span class=\"search-result-import-path\">PolarisOS/app/modules/entities/crud/mapper.js</span>",
    "function"
  ],
  [
    "polarisos/app/modules/utils/utils.js~traverse_and_execute",
    "function/index.html#static-function-traverse_and_execute",
    "<span>traverse_and_execute</span> <span class=\"search-result-import-path\">PolarisOS/app/modules/utils/utils.js</span>",
    "function"
  ],
  [
    "polarisos/app/modules/utils/utils.js~traverse_recreate_and_execute",
    "function/index.html#static-function-traverse_recreate_and_execute",
    "<span>traverse_recreate_and_execute</span> <span class=\"search-result-import-path\">PolarisOS/app/modules/utils/utils.js</span>",
    "function"
  ],
  [
    "polarisos/app/create_indices.js~update",
    "function/index.html#static-function-update",
    "<span>update</span> <span class=\"search-result-import-path\">PolarisOS/app/create_indices.js</span>",
    "function"
  ],
  [
    "polarisos/app/modules/utils/router.js~upload_middlewares",
    "function/index.html#static-function-upload_middlewares",
    "<span>upload_middlewares</span> <span class=\"search-result-import-path\">PolarisOS/app/modules/utils/router.js</span>",
    "function"
  ],
  [
    "polarisos/app/modules/entities/crud/controllers/index.js~validate",
    "function/index.html#static-function-validate",
    "<span>validate</span> <span class=\"search-result-import-path\">PolarisOS/app/modules/entities/crud/controllers/index.js</span>",
    "function"
  ],
  [
    "app/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "app/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "app/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "app/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "app/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "app/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "app/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "app/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "app/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "app/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "app/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "app/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "app/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "app/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "app/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "app/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "app/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "app/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "app/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "app/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "app/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "app/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "app/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "app/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "app/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "app/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "app/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "app/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "app/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "app/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "app/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "app/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "app/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "app/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "app/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "app/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "app/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "app/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "app/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "app/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "app/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "app/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "app/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "app/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "app/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "app/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "app/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "app/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "app/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "app/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "app/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "app/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "app/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "app/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "app/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "app/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "app/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "app/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "app/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "app/.external-ecmascript.js~String",
    "external"
  ],
  [
    "app/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "app/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "app/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "app/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "app/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "app/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "app/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "app/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "app/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "app/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "app/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "app/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "app/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "app/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "app/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "app/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "app/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "app/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "app/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "app/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "app/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "app/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "app/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "app/.external-ecmascript.js~function",
    "external"
  ],
  [
    "app/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "app/.external-ecmascript.js~null",
    "external"
  ],
  [
    "app/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "app/.external-ecmascript.js~number",
    "external"
  ],
  [
    "app/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "app/.external-ecmascript.js~object",
    "external"
  ],
  [
    "app/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "app/.external-ecmascript.js~string",
    "external"
  ],
  [
    "app/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "app/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "app/app.js",
    "file/app/app.js.html",
    "app/app.js",
    "file"
  ],
  [
    "app/config/all.js",
    "file/app/config/all.js.html",
    "app/config/all.js",
    "file"
  ],
  [
    "app/config/demo.js",
    "file/app/config/demo.js.html",
    "app/config/demo.js",
    "file"
  ],
  [
    "app/config/development.js",
    "file/app/config/development.js.html",
    "app/config/development.js",
    "file"
  ],
  [
    "app/config/index.js",
    "file/app/config/index.js.html",
    "app/config/index.js",
    "file"
  ],
  [
    "app/config/production.js",
    "file/app/config/production.js.html",
    "app/config/production.js",
    "file"
  ],
  [
    "app/config/testing.js",
    "file/app/config/testing.js.html",
    "app/config/testing.js",
    "file"
  ],
  [
    "app/create_indices.js",
    "file/app/create_indices.js.html",
    "app/create_indices.js",
    "file"
  ],
  [
    "app/csl_styles/register.js",
    "file/app/csl_styles/register.js.html",
    "app/csl_styles/register.js",
    "file"
  ],
  [
    "app/initializations/routes.js",
    "file/app/initializations/routes.js.html",
    "app/initializations/routes.js",
    "file"
  ],
  [
    "app/logger.js",
    "file/app/logger.js.html",
    "app/logger.js",
    "file"
  ],
  [
    "app/modules/3rdparty/rss/controllers.js",
    "file/app/modules/3rdparty/rss/controllers.js.html",
    "app/modules/3rdparty/rss/controllers.js",
    "file"
  ],
  [
    "app/modules/3rdparty/rss/routes.js",
    "file/app/modules/3rdparty/rss/routes.js.html",
    "app/modules/3rdparty/rss/routes.js",
    "file"
  ],
  [
    "app/modules/auth/access_schema.js",
    "file/app/modules/auth/access_schema.js.html",
    "app/modules/auth/access_schema.js",
    "file"
  ],
  [
    "app/modules/auth/right_enforcer.js",
    "file/app/modules/auth/right_enforcer.js.html",
    "app/modules/auth/right_enforcer.js",
    "file"
  ],
  [
    "app/modules/entities/apiuser/apiuser.js",
    "file/app/modules/entities/apiuser/apiuser.js.html",
    "app/modules/entities/apiuser/apiuser.js",
    "file"
  ],
  [
    "app/modules/entities/apiuser/controllers/index.js",
    "file/app/modules/entities/apiuser/controllers/index.js.html",
    "app/modules/entities/apiuser/controllers/index.js",
    "file"
  ],
  [
    "app/modules/entities/apiuser/index.js",
    "file/app/modules/entities/apiuser/index.js.html",
    "app/modules/entities/apiuser/index.js",
    "file"
  ],
  [
    "app/modules/entities/apiuser/routes/index.js",
    "file/app/modules/entities/apiuser/routes/index.js.html",
    "app/modules/entities/apiuser/routes/index.js",
    "file"
  ],
  [
    "app/modules/entities/chart/chart.js",
    "file/app/modules/entities/chart/chart.js.html",
    "app/modules/entities/chart/chart.js",
    "file"
  ],
  [
    "app/modules/entities/chart/controllers/index.js",
    "file/app/modules/entities/chart/controllers/index.js.html",
    "app/modules/entities/chart/controllers/index.js",
    "file"
  ],
  [
    "app/modules/entities/chart/index.js",
    "file/app/modules/entities/chart/index.js.html",
    "app/modules/entities/chart/index.js",
    "file"
  ],
  [
    "app/modules/entities/config/config.js",
    "file/app/modules/entities/config/config.js.html",
    "app/modules/entities/config/config.js",
    "file"
  ],
  [
    "app/modules/entities/config/controllers/index.js",
    "file/app/modules/entities/config/controllers/index.js.html",
    "app/modules/entities/config/controllers/index.js",
    "file"
  ],
  [
    "app/modules/entities/config/routes/index.js",
    "file/app/modules/entities/config/routes/index.js.html",
    "app/modules/entities/config/routes/index.js",
    "file"
  ],
  [
    "app/modules/entities/connector/connector.js",
    "file/app/modules/entities/connector/connector.js.html",
    "app/modules/entities/connector/connector.js",
    "file"
  ],
  [
    "app/modules/entities/connector/controllers/index.js",
    "file/app/modules/entities/connector/controllers/index.js.html",
    "app/modules/entities/connector/controllers/index.js",
    "file"
  ],
  [
    "app/modules/entities/connector/index.js",
    "file/app/modules/entities/connector/index.js.html",
    "app/modules/entities/connector/index.js",
    "file"
  ],
  [
    "app/modules/entities/connector/routes/index.js",
    "file/app/modules/entities/connector/routes/index.js.html",
    "app/modules/entities/connector/routes/index.js",
    "file"
  ],
  [
    "app/modules/entities/crud/aggregation.js",
    "file/app/modules/entities/crud/aggregation.js.html",
    "app/modules/entities/crud/aggregation.js",
    "file"
  ],
  [
    "app/modules/entities/crud/controllers/index.js",
    "file/app/modules/entities/crud/controllers/index.js.html",
    "app/modules/entities/crud/controllers/index.js",
    "file"
  ],
  [
    "app/modules/entities/crud/mapper.js",
    "file/app/modules/entities/crud/mapper.js.html",
    "app/modules/entities/crud/mapper.js",
    "file"
  ],
  [
    "app/modules/entities/crud/mapping.js",
    "file/app/modules/entities/crud/mapping.js.html",
    "app/modules/entities/crud/mapping.js",
    "file"
  ],
  [
    "app/modules/entities/crud/middlewares/index.js",
    "file/app/modules/entities/crud/middlewares/index.js.html",
    "app/modules/entities/crud/middlewares/index.js",
    "file"
  ],
  [
    "app/modules/entities/crud/odm.js",
    "file/app/modules/entities/crud/odm.js.html",
    "app/modules/entities/crud/odm.js",
    "file"
  ],
  [
    "app/modules/entities/crud/odm.js~odm#_client",
    "class/app/modules/entities/crud/odm.js~ODM.html#instance-member-_client",
    "app/modules/entities/crud/odm.js~ODM#_client",
    "member"
  ],
  [
    "app/modules/entities/crud/odm.js~odm#_db",
    "class/app/modules/entities/crud/odm.js~ODM.html#instance-member-_db",
    "app/modules/entities/crud/odm.js~ODM#_db",
    "member"
  ],
  [
    "app/modules/entities/crud/odm.js~odm#_handle_population",
    "class/app/modules/entities/crud/odm.js~ODM.html#instance-method-_handle_population",
    "app/modules/entities/crud/odm.js~ODM#_handle_population",
    "method"
  ],
  [
    "app/modules/entities/crud/odm.js~odm#_id",
    "class/app/modules/entities/crud/odm.js~ODM.html#instance-member-_id",
    "app/modules/entities/crud/odm.js~ODM#_id",
    "member"
  ],
  [
    "app/modules/entities/crud/odm.js~odm#_index",
    "class/app/modules/entities/crud/odm.js~ODM.html#instance-member-_index",
    "app/modules/entities/crud/odm.js~ODM#_index",
    "member"
  ],
  [
    "app/modules/entities/crud/odm.js~odm#_model",
    "class/app/modules/entities/crud/odm.js~ODM.html#instance-member-_model",
    "app/modules/entities/crud/odm.js~ODM#_model",
    "member"
  ],
  [
    "app/modules/entities/crud/odm.js~odm#_type",
    "class/app/modules/entities/crud/odm.js~ODM.html#instance-member-_type",
    "app/modules/entities/crud/odm.js~ODM#_type",
    "member"
  ],
  [
    "app/modules/entities/crud/odm.js~odm#constructor",
    "class/app/modules/entities/crud/odm.js~ODM.html#instance-constructor-constructor",
    "app/modules/entities/crud/odm.js~ODM#constructor",
    "method"
  ],
  [
    "app/modules/entities/crud/odm.js~odm#db",
    "class/app/modules/entities/crud/odm.js~ODM.html#instance-get-db",
    "app/modules/entities/crud/odm.js~ODM#db",
    "member"
  ],
  [
    "app/modules/entities/crud/odm.js~odm#db",
    "class/app/modules/entities/crud/odm.js~ODM.html#instance-set-db",
    "app/modules/entities/crud/odm.js~ODM#db",
    "member"
  ],
  [
    "app/modules/entities/crud/odm.js~odm#id",
    "class/app/modules/entities/crud/odm.js~ODM.html#instance-get-id",
    "app/modules/entities/crud/odm.js~ODM#id",
    "member"
  ],
  [
    "app/modules/entities/crud/odm.js~odm#index",
    "class/app/modules/entities/crud/odm.js~ODM.html#instance-get-index",
    "app/modules/entities/crud/odm.js~ODM#index",
    "member"
  ],
  [
    "app/modules/entities/crud/odm.js~odm#mapping",
    "class/app/modules/entities/crud/odm.js~ODM.html#instance-get-mapping",
    "app/modules/entities/crud/odm.js~ODM#mapping",
    "member"
  ],
  [
    "app/modules/entities/crud/odm.js~odm#messages",
    "class/app/modules/entities/crud/odm.js~ODM.html#instance-get-messages",
    "app/modules/entities/crud/odm.js~ODM#messages",
    "member"
  ],
  [
    "app/modules/entities/crud/odm.js~odm#model",
    "class/app/modules/entities/crud/odm.js~ODM.html#instance-get-model",
    "app/modules/entities/crud/odm.js~ODM#model",
    "member"
  ],
  [
    "app/modules/entities/crud/odm.js~odm#name",
    "class/app/modules/entities/crud/odm.js~ODM.html#instance-get-name",
    "app/modules/entities/crud/odm.js~ODM#name",
    "member"
  ],
  [
    "app/modules/entities/crud/odm.js~odm#ocreate",
    "class/app/modules/entities/crud/odm.js~ODM.html#instance-method-ocreate",
    "app/modules/entities/crud/odm.js~ODM#ocreate",
    "method"
  ],
  [
    "app/modules/entities/crud/odm.js~odm#oupdate",
    "class/app/modules/entities/crud/odm.js~ODM.html#instance-method-oupdate",
    "app/modules/entities/crud/odm.js~ODM#oupdate",
    "method"
  ],
  [
    "app/modules/entities/crud/odm.js~odm#post_create_hook",
    "class/app/modules/entities/crud/odm.js~ODM.html#instance-method-post_create_hook",
    "app/modules/entities/crud/odm.js~ODM#post_create_hook",
    "method"
  ],
  [
    "app/modules/entities/crud/odm.js~odm#post_read_hook",
    "class/app/modules/entities/crud/odm.js~ODM.html#instance-method-post_read_hook",
    "app/modules/entities/crud/odm.js~ODM#post_read_hook",
    "method"
  ],
  [
    "app/modules/entities/crud/odm.js~odm#post_update_hook",
    "class/app/modules/entities/crud/odm.js~ODM.html#instance-method-post_update_hook",
    "app/modules/entities/crud/odm.js~ODM#post_update_hook",
    "method"
  ],
  [
    "app/modules/entities/crud/odm.js~odm#pre_read_hook",
    "class/app/modules/entities/crud/odm.js~ODM.html#instance-method-pre_read_hook",
    "app/modules/entities/crud/odm.js~ODM#pre_read_hook",
    "method"
  ],
  [
    "app/modules/entities/crud/odm.js~odm#read",
    "class/app/modules/entities/crud/odm.js~ODM.html#instance-method-read",
    "app/modules/entities/crud/odm.js~ODM#read",
    "method"
  ],
  [
    "app/modules/entities/crud/odm.js~odm#source",
    "class/app/modules/entities/crud/odm.js~ODM.html#instance-get-source",
    "app/modules/entities/crud/odm.js~ODM#source",
    "member"
  ],
  [
    "app/modules/entities/crud/odm.js~odm#tojson",
    "class/app/modules/entities/crud/odm.js~ODM.html#instance-method-toJSON",
    "app/modules/entities/crud/odm.js~ODM#toJSON",
    "method"
  ],
  [
    "app/modules/entities/crud/odm.js~odm#type",
    "class/app/modules/entities/crud/odm.js~ODM.html#instance-get-type",
    "app/modules/entities/crud/odm.js~ODM#type",
    "member"
  ],
  [
    "app/modules/entities/crud/odm.js~odm._bulk_create_or_update",
    "class/app/modules/entities/crud/odm.js~ODM.html#static-method-_bulk_create_or_update",
    "app/modules/entities/crud/odm.js~ODM._bulk_create_or_update",
    "method"
  ],
  [
    "app/modules/entities/crud/odm.js~odm._create_or_update",
    "class/app/modules/entities/crud/odm.js~ODM.html#static-method-_create_or_update",
    "app/modules/entities/crud/odm.js~ODM._create_or_update",
    "method"
  ],
  [
    "app/modules/entities/crud/odm.js~odm.bulk_create",
    "class/app/modules/entities/crud/odm.js~ODM.html#static-method-bulk_create",
    "app/modules/entities/crud/odm.js~ODM.bulk_create",
    "method"
  ],
  [
    "app/modules/entities/crud/odm.js~odm.bulk_update",
    "class/app/modules/entities/crud/odm.js~ODM.html#static-method-bulk_update",
    "app/modules/entities/crud/odm.js~ODM.bulk_update",
    "method"
  ],
  [
    "app/modules/entities/crud/odm.js~odm.count",
    "class/app/modules/entities/crud/odm.js~ODM.html#static-method-count",
    "app/modules/entities/crud/odm.js~ODM.count",
    "method"
  ],
  [
    "app/modules/entities/crud/odm.js~odm.create",
    "class/app/modules/entities/crud/odm.js~ODM.html#static-method-create",
    "app/modules/entities/crud/odm.js~ODM.create",
    "method"
  ],
  [
    "app/modules/entities/crud/odm.js~odm.deletebyquery",
    "class/app/modules/entities/crud/odm.js~ODM.html#static-method-deleteByQuery",
    "app/modules/entities/crud/odm.js~ODM.deleteByQuery",
    "method"
  ],
  [
    "app/modules/entities/crud/odm.js~odm.fetch_mapping",
    "class/app/modules/entities/crud/odm.js~ODM.html#static-method-fetch_mapping",
    "app/modules/entities/crud/odm.js~ODM.fetch_mapping",
    "method"
  ],
  [
    "app/modules/entities/crud/odm.js~odm.fetch_settings",
    "class/app/modules/entities/crud/odm.js~ODM.html#static-method-fetch_settings",
    "app/modules/entities/crud/odm.js~ODM.fetch_settings",
    "method"
  ],
  [
    "app/modules/entities/crud/odm.js~odm.format_hit",
    "class/app/modules/entities/crud/odm.js~ODM.html#static-method-format_hit",
    "app/modules/entities/crud/odm.js~ODM.format_hit",
    "method"
  ],
  [
    "app/modules/entities/crud/odm.js~odm.pre_create_hook",
    "class/app/modules/entities/crud/odm.js~ODM.html#static-method-pre_create_hook",
    "app/modules/entities/crud/odm.js~ODM.pre_create_hook",
    "method"
  ],
  [
    "app/modules/entities/crud/odm.js~odm.pre_update_hook",
    "class/app/modules/entities/crud/odm.js~ODM.html#static-method-pre_update_hook",
    "app/modules/entities/crud/odm.js~ODM.pre_update_hook",
    "method"
  ],
  [
    "app/modules/entities/crud/odm.js~odm.read",
    "class/app/modules/entities/crud/odm.js~ODM.html#static-method-read",
    "app/modules/entities/crud/odm.js~ODM.read",
    "method"
  ],
  [
    "app/modules/entities/crud/odm.js~odm.remove",
    "class/app/modules/entities/crud/odm.js~ODM.html#static-method-remove",
    "app/modules/entities/crud/odm.js~ODM.remove",
    "method"
  ],
  [
    "app/modules/entities/crud/odm.js~odm.search",
    "class/app/modules/entities/crud/odm.js~ODM.html#static-method-search",
    "app/modules/entities/crud/odm.js~ODM.search",
    "method"
  ],
  [
    "app/modules/entities/crud/odm.js~odm.update",
    "class/app/modules/entities/crud/odm.js~ODM.html#static-method-update",
    "app/modules/entities/crud/odm.js~ODM.update",
    "method"
  ],
  [
    "app/modules/entities/crud/query.js",
    "file/app/modules/entities/crud/query.js.html",
    "app/modules/entities/crud/query.js",
    "file"
  ],
  [
    "app/modules/entities/entity/entity.js",
    "file/app/modules/entities/entity/entity.js.html",
    "app/modules/entities/entity/entity.js",
    "file"
  ],
  [
    "app/modules/entities/exporter/controllers/hal.js",
    "file/app/modules/entities/exporter/controllers/hal.js.html",
    "app/modules/entities/exporter/controllers/hal.js",
    "file"
  ],
  [
    "app/modules/entities/exporter/controllers/repec.js",
    "file/app/modules/entities/exporter/controllers/repec.js.html",
    "app/modules/entities/exporter/controllers/repec.js",
    "file"
  ],
  [
    "app/modules/entities/exporter/exporter.js",
    "file/app/modules/entities/exporter/exporter.js.html",
    "app/modules/entities/exporter/exporter.js",
    "file"
  ],
  [
    "app/modules/entities/exporter/index.js",
    "file/app/modules/entities/exporter/index.js.html",
    "app/modules/entities/exporter/index.js",
    "file"
  ],
  [
    "app/modules/entities/exporter/pipeline/bibtex_collector.js",
    "file/app/modules/entities/exporter/pipeline/bibtex_collector.js.html",
    "app/modules/entities/exporter/pipeline/bibtex_collector.js",
    "file"
  ],
  [
    "app/modules/entities/exporter/pipeline/bibtex_pipeline.js",
    "file/app/modules/entities/exporter/pipeline/bibtex_pipeline.js.html",
    "app/modules/entities/exporter/pipeline/bibtex_pipeline.js",
    "file"
  ],
  [
    "app/modules/entities/exporter/pipeline/csv_collector.js",
    "file/app/modules/entities/exporter/pipeline/csv_collector.js.html",
    "app/modules/entities/exporter/pipeline/csv_collector.js",
    "file"
  ],
  [
    "app/modules/entities/form/controllers/index.js",
    "file/app/modules/entities/form/controllers/index.js.html",
    "app/modules/entities/form/controllers/index.js",
    "file"
  ],
  [
    "app/modules/entities/form/form.js",
    "file/app/modules/entities/form/form.js.html",
    "app/modules/entities/form/form.js",
    "file"
  ],
  [
    "app/modules/entities/form/routes/index.js",
    "file/app/modules/entities/form/routes/index.js.html",
    "app/modules/entities/form/routes/index.js",
    "file"
  ],
  [
    "app/modules/entities/function/controllers/index.js",
    "file/app/modules/entities/function/controllers/index.js.html",
    "app/modules/entities/function/controllers/index.js",
    "file"
  ],
  [
    "app/modules/entities/function/function.js",
    "file/app/modules/entities/function/function.js.html",
    "app/modules/entities/function/function.js",
    "file"
  ],
  [
    "app/modules/entities/function/routes/index.js",
    "file/app/modules/entities/function/routes/index.js.html",
    "app/modules/entities/function/routes/index.js",
    "file"
  ],
  [
    "app/modules/entities/identifier/controllers/index.js",
    "file/app/modules/entities/identifier/controllers/index.js.html",
    "app/modules/entities/identifier/controllers/index.js",
    "file"
  ],
  [
    "app/modules/entities/identifier/identifier.js",
    "file/app/modules/entities/identifier/identifier.js.html",
    "app/modules/entities/identifier/identifier.js",
    "file"
  ],
  [
    "app/modules/entities/identifier/index.js",
    "file/app/modules/entities/identifier/index.js.html",
    "app/modules/entities/identifier/index.js",
    "file"
  ],
  [
    "app/modules/entities/importer/importer.js",
    "file/app/modules/entities/importer/importer.js.html",
    "app/modules/entities/importer/importer.js",
    "file"
  ],
  [
    "app/modules/entities/importer/index.js",
    "file/app/modules/entities/importer/index.js.html",
    "app/modules/entities/importer/index.js",
    "file"
  ],
  [
    "app/modules/entities/lang/controllers/index.js",
    "file/app/modules/entities/lang/controllers/index.js.html",
    "app/modules/entities/lang/controllers/index.js",
    "file"
  ],
  [
    "app/modules/entities/lang/lang.js",
    "file/app/modules/entities/lang/lang.js.html",
    "app/modules/entities/lang/lang.js",
    "file"
  ],
  [
    "app/modules/entities/lang/routes/index.js",
    "file/app/modules/entities/lang/routes/index.js.html",
    "app/modules/entities/lang/routes/index.js",
    "file"
  ],
  [
    "app/modules/entities/mail_template/controllers/index.js",
    "file/app/modules/entities/mail_template/controllers/index.js.html",
    "app/modules/entities/mail_template/controllers/index.js",
    "file"
  ],
  [
    "app/modules/entities/mail_template/index.js",
    "file/app/modules/entities/mail_template/index.js.html",
    "app/modules/entities/mail_template/index.js",
    "file"
  ],
  [
    "app/modules/entities/mail_template/mail_template.js",
    "file/app/modules/entities/mail_template/mail_template.js.html",
    "app/modules/entities/mail_template/mail_template.js",
    "file"
  ],
  [
    "app/modules/entities/menu/controllers/index.js",
    "file/app/modules/entities/menu/controllers/index.js.html",
    "app/modules/entities/menu/controllers/index.js",
    "file"
  ],
  [
    "app/modules/entities/menu/index.js",
    "file/app/modules/entities/menu/index.js.html",
    "app/modules/entities/menu/index.js",
    "file"
  ],
  [
    "app/modules/entities/menu/menu.js",
    "file/app/modules/entities/menu/menu.js.html",
    "app/modules/entities/menu/menu.js",
    "file"
  ],
  [
    "app/modules/entities/mswpublication/controllers/index.js",
    "file/app/modules/entities/mswpublication/controllers/index.js.html",
    "app/modules/entities/mswpublication/controllers/index.js",
    "file"
  ],
  [
    "app/modules/entities/mswpublication/index.js",
    "file/app/modules/entities/mswpublication/index.js.html",
    "app/modules/entities/mswpublication/index.js",
    "file"
  ],
  [
    "app/modules/entities/mswpublication/mswpublication.js",
    "file/app/modules/entities/mswpublication/mswpublication.js.html",
    "app/modules/entities/mswpublication/mswpublication.js",
    "file"
  ],
  [
    "app/modules/entities/page/controllers/index.js",
    "file/app/modules/entities/page/controllers/index.js.html",
    "app/modules/entities/page/controllers/index.js",
    "file"
  ],
  [
    "app/modules/entities/page/index.js",
    "file/app/modules/entities/page/index.js.html",
    "app/modules/entities/page/index.js",
    "file"
  ],
  [
    "app/modules/entities/page/page.js",
    "file/app/modules/entities/page/page.js.html",
    "app/modules/entities/page/page.js",
    "file"
  ],
  [
    "app/modules/entities/pipeline/controllers/index.js",
    "file/app/modules/entities/pipeline/controllers/index.js.html",
    "app/modules/entities/pipeline/controllers/index.js",
    "file"
  ],
  [
    "app/modules/entities/pipeline/pipeline.js",
    "file/app/modules/entities/pipeline/pipeline.js.html",
    "app/modules/entities/pipeline/pipeline.js",
    "file"
  ],
  [
    "app/modules/entities/pipeline/routes/index.js",
    "file/app/modules/entities/pipeline/routes/index.js.html",
    "app/modules/entities/pipeline/routes/index.js",
    "file"
  ],
  [
    "app/modules/entities/publication/index.js",
    "file/app/modules/entities/publication/index.js.html",
    "app/modules/entities/publication/index.js",
    "file"
  ],
  [
    "app/modules/entities/publication/models/pipeline_diffusion.js",
    "file/app/modules/entities/publication/models/pipeline_diffusion.js.html",
    "app/modules/entities/publication/models/pipeline_diffusion.js",
    "file"
  ],
  [
    "app/modules/entities/publication/models/pipeline_type_files.js",
    "file/app/modules/entities/publication/models/pipeline_type_files.js.html",
    "app/modules/entities/publication/models/pipeline_type_files.js",
    "file"
  ],
  [
    "app/modules/entities/publication/publication.js",
    "file/app/modules/entities/publication/publication.js.html",
    "app/modules/entities/publication/publication.js",
    "file"
  ],
  [
    "app/modules/entities/query/controllers/index.js",
    "file/app/modules/entities/query/controllers/index.js.html",
    "app/modules/entities/query/controllers/index.js",
    "file"
  ],
  [
    "app/modules/entities/query/index.js",
    "file/app/modules/entities/query/index.js.html",
    "app/modules/entities/query/index.js",
    "file"
  ],
  [
    "app/modules/entities/query/query.js",
    "file/app/modules/entities/query/query.js.html",
    "app/modules/entities/query/query.js",
    "file"
  ],
  [
    "app/modules/entities/role/controllers/index.js",
    "file/app/modules/entities/role/controllers/index.js.html",
    "app/modules/entities/role/controllers/index.js",
    "file"
  ],
  [
    "app/modules/entities/role/index.js",
    "file/app/modules/entities/role/index.js.html",
    "app/modules/entities/role/index.js",
    "file"
  ],
  [
    "app/modules/entities/role/role.js",
    "file/app/modules/entities/role/role.js.html",
    "app/modules/entities/role/role.js",
    "file"
  ],
  [
    "app/modules/entities/template/controllers/index.js",
    "file/app/modules/entities/template/controllers/index.js.html",
    "app/modules/entities/template/controllers/index.js",
    "file"
  ],
  [
    "app/modules/entities/template/index.js",
    "file/app/modules/entities/template/index.js.html",
    "app/modules/entities/template/index.js",
    "file"
  ],
  [
    "app/modules/entities/template/template.js",
    "file/app/modules/entities/template/template.js.html",
    "app/modules/entities/template/template.js",
    "file"
  ],
  [
    "app/modules/entities/user/controllers/index.js",
    "file/app/modules/entities/user/controllers/index.js.html",
    "app/modules/entities/user/controllers/index.js",
    "file"
  ],
  [
    "app/modules/entities/user/index.js",
    "file/app/modules/entities/user/index.js.html",
    "app/modules/entities/user/index.js",
    "file"
  ],
  [
    "app/modules/entities/user/routes/index.js",
    "file/app/modules/entities/user/routes/index.js.html",
    "app/modules/entities/user/routes/index.js",
    "file"
  ],
  [
    "app/modules/entities/user/user.js",
    "file/app/modules/entities/user/user.js.html",
    "app/modules/entities/user/user.js",
    "file"
  ],
  [
    "app/modules/entities/widget/controllers/index.js",
    "file/app/modules/entities/widget/controllers/index.js.html",
    "app/modules/entities/widget/controllers/index.js",
    "file"
  ],
  [
    "app/modules/entities/widget/index.js",
    "file/app/modules/entities/widget/index.js.html",
    "app/modules/entities/widget/index.js",
    "file"
  ],
  [
    "app/modules/entities/widget/widget.js",
    "file/app/modules/entities/widget/widget.js.html",
    "app/modules/entities/widget/widget.js",
    "file"
  ],
  [
    "app/modules/exceptions/generic.js",
    "file/app/modules/exceptions/generic.js.html",
    "app/modules/exceptions/generic.js",
    "file"
  ],
  [
    "app/modules/pipeline/completer/completer.js",
    "file/app/modules/pipeline/completer/completer.js.html",
    "app/modules/pipeline/completer/completer.js",
    "file"
  ],
  [
    "app/modules/pipeline/completer/complfunctions/index.js",
    "file/app/modules/pipeline/completer/complfunctions/index.js.html",
    "app/modules/pipeline/completer/complfunctions/index.js",
    "file"
  ],
  [
    "app/modules/pipeline/formatter/formatfunctions/index.js",
    "file/app/modules/pipeline/formatter/formatfunctions/index.js.html",
    "app/modules/pipeline/formatter/formatfunctions/index.js",
    "file"
  ],
  [
    "app/modules/pipeline/formatter/formatter.js",
    "file/app/modules/pipeline/formatter/formatter.js.html",
    "app/modules/pipeline/formatter/formatter.js",
    "file"
  ],
  [
    "app/modules/pipeline/pipeline.js",
    "file/app/modules/pipeline/pipeline.js.html",
    "app/modules/pipeline/pipeline.js",
    "file"
  ],
  [
    "app/modules/pipeline/pipeline.js~pipeline._action",
    "class/app/modules/pipeline/pipeline.js~Pipeline.html#static-method-_action",
    "app/modules/pipeline/pipeline.js~Pipeline._action",
    "method"
  ],
  [
    "app/modules/pipeline/pipeline.js~pipeline._check_if_entity_exists",
    "class/app/modules/pipeline/pipeline.js~Pipeline.html#static-method-_check_if_entity_exists",
    "app/modules/pipeline/pipeline.js~Pipeline._check_if_entity_exists",
    "method"
  ],
  [
    "app/modules/pipeline/pipeline.js~pipeline._evaluate_pipeline",
    "class/app/modules/pipeline/pipeline.js~Pipeline.html#static-method-_evaluate_pipeline",
    "app/modules/pipeline/pipeline.js~Pipeline._evaluate_pipeline",
    "method"
  ],
  [
    "app/modules/pipeline/pipeline.js~pipeline._filter",
    "class/app/modules/pipeline/pipeline.js~Pipeline.html#static-method-_filter",
    "app/modules/pipeline/pipeline.js~Pipeline._filter",
    "method"
  ],
  [
    "app/modules/pipeline/pipeline.js~pipeline._format_range",
    "class/app/modules/pipeline/pipeline.js~Pipeline.html#static-method-_format_range",
    "app/modules/pipeline/pipeline.js~Pipeline._format_range",
    "method"
  ],
  [
    "app/modules/pipeline/pipeline.js~pipeline._merge_defaults",
    "class/app/modules/pipeline/pipeline.js~Pipeline.html#static-method-_merge_defaults",
    "app/modules/pipeline/pipeline.js~Pipeline._merge_defaults",
    "method"
  ],
  [
    "app/modules/pipeline/pipeline.js~pipeline._merge_put",
    "class/app/modules/pipeline/pipeline.js~Pipeline.html#static-method-_merge_put",
    "app/modules/pipeline/pipeline.js~Pipeline._merge_put",
    "method"
  ],
  [
    "app/modules/pipeline/pipeline.js~pipeline._papply",
    "class/app/modules/pipeline/pipeline.js~Pipeline.html#static-method-_papply",
    "app/modules/pipeline/pipeline.js~Pipeline._papply",
    "method"
  ],
  [
    "app/modules/pipeline/pipeline.js~pipeline._reset",
    "class/app/modules/pipeline/pipeline.js~Pipeline.html#static-method-_reset",
    "app/modules/pipeline/pipeline.js~Pipeline._reset",
    "method"
  ],
  [
    "app/modules/pipeline/pipeline.js~pipeline.check",
    "class/app/modules/pipeline/pipeline.js~Pipeline.html#static-method-check",
    "app/modules/pipeline/pipeline.js~Pipeline.check",
    "method"
  ],
  [
    "app/modules/pipeline/pipeline.js~pipeline.complete",
    "class/app/modules/pipeline/pipeline.js~Pipeline.html#static-method-complete",
    "app/modules/pipeline/pipeline.js~Pipeline.complete",
    "method"
  ],
  [
    "app/modules/pipeline/pipeline.js~pipeline.defaults",
    "class/app/modules/pipeline/pipeline.js~Pipeline.html#static-method-defaults",
    "app/modules/pipeline/pipeline.js~Pipeline.defaults",
    "method"
  ],
  [
    "app/modules/pipeline/pipeline.js~pipeline.filter",
    "class/app/modules/pipeline/pipeline.js~Pipeline.html#static-method-filter",
    "app/modules/pipeline/pipeline.js~Pipeline.filter",
    "method"
  ],
  [
    "app/modules/pipeline/pipeline.js~pipeline.format",
    "class/app/modules/pipeline/pipeline.js~Pipeline.html#static-method-format",
    "app/modules/pipeline/pipeline.js~Pipeline.format",
    "method"
  ],
  [
    "app/modules/pipeline/pipeline.js~pipeline.memoize_model",
    "class/app/modules/pipeline/pipeline.js~Pipeline.html#static-method-memoize_model",
    "app/modules/pipeline/pipeline.js~Pipeline.memoize_model",
    "method"
  ],
  [
    "app/modules/pipeline/pipeline.js~pipeline.merge",
    "class/app/modules/pipeline/pipeline.js~Pipeline.html#static-method-merge",
    "app/modules/pipeline/pipeline.js~Pipeline.merge",
    "method"
  ],
  [
    "app/modules/pipeline/pipeline.js~pipeline.reset",
    "class/app/modules/pipeline/pipeline.js~Pipeline.html#static-method-reset",
    "app/modules/pipeline/pipeline.js~Pipeline.reset",
    "method"
  ],
  [
    "app/modules/pipeline/pipeline.js~pipeline.transform",
    "class/app/modules/pipeline/pipeline.js~Pipeline.html#static-method-transform",
    "app/modules/pipeline/pipeline.js~Pipeline.transform",
    "method"
  ],
  [
    "app/modules/pipeline/pipeline.js~pipeline.validate",
    "class/app/modules/pipeline/pipeline.js~Pipeline.html#static-method-validate",
    "app/modules/pipeline/pipeline.js~Pipeline.validate",
    "method"
  ],
  [
    "app/modules/pipeline/transformer/transformer.js",
    "file/app/modules/pipeline/transformer/transformer.js.html",
    "app/modules/pipeline/transformer/transformer.js",
    "file"
  ],
  [
    "app/modules/pipeline/transformer/transfunctions/index.js",
    "file/app/modules/pipeline/transformer/transfunctions/index.js.html",
    "app/modules/pipeline/transformer/transfunctions/index.js",
    "file"
  ],
  [
    "app/modules/pipeline/validator/valfunctions/checks.js",
    "file/app/modules/pipeline/validator/valfunctions/checks.js.html",
    "app/modules/pipeline/validator/valfunctions/checks.js",
    "file"
  ],
  [
    "app/modules/pipeline/validator/valfunctions/index.js",
    "file/app/modules/pipeline/validator/valfunctions/index.js.html",
    "app/modules/pipeline/validator/valfunctions/index.js",
    "file"
  ],
  [
    "app/modules/pipeline/validator/validator.js",
    "file/app/modules/pipeline/validator/validator.js.html",
    "app/modules/pipeline/validator/validator.js",
    "file"
  ],
  [
    "app/modules/pipeline/validator/validator.js~validator#_options",
    "class/app/modules/pipeline/validator/validator.js~Validator.html#instance-member-_options",
    "app/modules/pipeline/validator/validator.js~Validator#_options",
    "member"
  ],
  [
    "app/modules/pipeline/validator/validator.js~validator#_validate_with_validator",
    "class/app/modules/pipeline/validator/validator.js~Validator.html#instance-method-_validate_with_validator",
    "app/modules/pipeline/validator/validator.js~Validator#_validate_with_validator",
    "method"
  ],
  [
    "app/modules/pipeline/validator/validator.js~validator#constructor",
    "class/app/modules/pipeline/validator/validator.js~Validator.html#instance-constructor-constructor",
    "app/modules/pipeline/validator/validator.js~Validator#constructor",
    "method"
  ],
  [
    "app/modules/pipeline/validator/validator.js~validator#validate",
    "class/app/modules/pipeline/validator/validator.js~Validator.html#instance-method-validate",
    "app/modules/pipeline/validator/validator.js~Validator#validate",
    "method"
  ],
  [
    "app/modules/pipeline/validator/validator.js~validator._compose_custom_errors",
    "class/app/modules/pipeline/validator/validator.js~Validator.html#static-method-_compose_custom_errors",
    "app/modules/pipeline/validator/validator.js~Validator._compose_custom_errors",
    "method"
  ],
  [
    "app/modules/pipeline/validator/validator.js~validator._compose_joi_errors",
    "class/app/modules/pipeline/validator/validator.js~Validator.html#static-method-_compose_joi_errors",
    "app/modules/pipeline/validator/validator.js~Validator._compose_joi_errors",
    "method"
  ],
  [
    "app/modules/pipeline/validator/validator.js~validator._isjoi",
    "class/app/modules/pipeline/validator/validator.js~Validator.html#static-method-_isJoi",
    "app/modules/pipeline/validator/validator.js~Validator._isJoi",
    "method"
  ],
  [
    "app/modules/rate_limit/limit.js",
    "file/app/modules/rate_limit/limit.js.html",
    "app/modules/rate_limit/limit.js",
    "file"
  ],
  [
    "app/modules/rate_limit/memory_store.js",
    "file/app/modules/rate_limit/memory_store.js.html",
    "app/modules/rate_limit/memory_store.js",
    "file"
  ],
  [
    "app/modules/rate_limit/rate_limit.js",
    "file/app/modules/rate_limit/rate_limit.js.html",
    "app/modules/rate_limit/rate_limit.js",
    "file"
  ],
  [
    "app/modules/utils/auth.js",
    "file/app/modules/utils/auth.js.html",
    "app/modules/utils/auth.js",
    "file"
  ],
  [
    "app/modules/utils/bibtex.js",
    "file/app/modules/utils/bibtex.js.html",
    "app/modules/utils/bibtex.js",
    "file"
  ],
  [
    "app/modules/utils/cache.js",
    "file/app/modules/utils/cache.js.html",
    "app/modules/utils/cache.js",
    "file"
  ],
  [
    "app/modules/utils/crypto.js",
    "file/app/modules/utils/crypto.js.html",
    "app/modules/utils/crypto.js",
    "file"
  ],
  [
    "app/modules/utils/lang.js",
    "file/app/modules/utils/lang.js.html",
    "app/modules/utils/lang.js",
    "file"
  ],
  [
    "app/modules/utils/mailer.js",
    "file/app/modules/utils/mailer.js.html",
    "app/modules/utils/mailer.js",
    "file"
  ],
  [
    "app/modules/utils/router.js",
    "file/app/modules/utils/router.js.html",
    "app/modules/utils/router.js",
    "file"
  ],
  [
    "app/modules/utils/streams.js",
    "file/app/modules/utils/streams.js.html",
    "app/modules/utils/streams.js",
    "file"
  ],
  [
    "app/modules/utils/templating.js",
    "file/app/modules/utils/templating.js.html",
    "app/modules/utils/templating.js",
    "file"
  ],
  [
    "app/modules/utils/uploads.js",
    "file/app/modules/utils/uploads.js.html",
    "app/modules/utils/uploads.js",
    "file"
  ],
  [
    "app/modules/utils/utils.js",
    "file/app/modules/utils/utils.js.html",
    "app/modules/utils/utils.js",
    "file"
  ],
  [
    "app/modules/utils/web.js",
    "file/app/modules/utils/web.js.html",
    "app/modules/utils/web.js",
    "file"
  ],
  [
    "app/modules/utils/xml.js",
    "file/app/modules/utils/xml.js.html",
    "app/modules/utils/xml.js",
    "file"
  ]
]