module.exports = {
    admin: '/admin',
    user: '/admin/user',
    review: '/admin/review',
    datasource: '/admin/datasource',
    datainstance: '/admin/datasource/:datainstance',
    publication: '/admin/publication',
    csl: '/admin/csl',
    form: '/admin/form',
    menu: '/admin/menu',
    lang: '/admin/lang',
    external_repo: '/admin/external_repository',
    export_format: '/admin/export_format',
    handle_id: '/admin/handle_id',
    api: '/admin/api',
    config: '/admin/config',
};
